### PR TITLE
Fixes for python 3, tested with 3.7.4 and rfcat with python3 fixes

### PR DESCRIPTION
**Pull request by mcdan**
Fixes a bunch of simple syntax issues with python3. Sorry I'm not really a python developer not sure if there is a better way to make this work with python2 as well.

### CODE REVIEW

**Comment by chinemys** [comment]
your modification for python3 works fine, thanks friend

**Comment by kevtheskin** [comment]
Hello there, How do I save a copy of the updated RFcrack.py please.  I am just and old noobie. Thanks Kev

**Comment by DroidKali** [comment]
@kevtheskin just follow these steps
```
git clone https://github.com/cclabsInc/RFCrack.git

cd RFCrack

wget https://github.com/cclabsInc/RFCrack/commit/bce37e365a214111d01e8556d0995323fa8a2421.patch -O rfcrack.patch

patch -p1 < rfcrack.patch

python3 RFCrack.py -i
```
It works fine for me

**Comment by kevtheskin** [comment]
> @kevtheskin just follow these steps
> 
> ```
> git clone https://github.com/cclabsInc/RFCrack.git
> 
> cd RFCrack
> 
> wget https://github.com/cclabsInc/RFCrack/commit/bce37e365a214111d01e8556d0995323fa8a2421.patch -O rfcrack.patch
> 
> patch -p1 < rfcrack.patch
> 
> python3 RFCrack.py -i
> ```
> 
> It works fine for me

Hi there thanks for the reply,  unfortunately it didn't fully work  this is the error generated
Error in resetup():ChipconUsbTimeoutException()
Traceback (most recent call last):
  File "/home/pentest/radio/RFCrack/RFCrack.py", line 165, in <module>
    d = RfCat(idx=0)
  File "/usr/lib/python3/dist-packages/rflib/chipcon_nic.py", line 317, in __init__
    self.mhz = CHIPmhz.get(self.chipnum)
AttributeError: 'RfCat' object has no attribute 'chipnum'
===== RESETUP set from recv thread
zsh: segmentation fault  sudo python3 RFCrack.py -i -F 433920000

Any help much appreciated . Cheers Kev

**Pull request closed without merging**
